### ISSUE TITLE
Issues with S6_matchms_spec2vec.py 

### ISSUE THREAD

**Issue by oyileo** [volvox292/Nicotiana_metabolomics#1]
Hi :
    I tried to reproduce your process.
    After  create a final set of 1,066,512 composite spectra (Script 5) , I used S6 in Linux.
    I create a conda environment called matchms. refer to : https://github.com/matchms/matchms

    `conda create --name matchms python=3.9
    conda activate matchms
    conda install --channel bioconda --channel conda-forge matchms `

    And
 
    `pip install gensim
    pip install spec2vec
    pip install joblib`

   And next, this is my directory:

    `(matchms-python3.8) yang@yang-ubuntu:~/project/A4-Nicotiana/result/06-local_model/S6$ tree
.
├── GNPS-clean_data.mgf
├── S6_matchms_spec2vec.py
└── TOTAL_COMPOUNDS_DB.energies_merged_name.mgf

0 directories, 3 files`

    Next, use 
    `python S6_matchms_spec2vec.py`

    Then, error:
    `Traceback (most recent call last):
  File "S6_matchms_spec2vec.py", line 322, in <module>
    model = gensim.models.Word2Vec.load("GNPS_CFMID.min10peaks.model")
  File "/home/yang/software/Program_File/miniconda3/envs/matchms-python3.8/lib/python3.8/site-packages/gensim/models/word2vec.py", line 1953, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "/home/yang/software/Program_File/miniconda3/envs/matchms-python3.8/lib/python3.8/site-packages/gensim/utils.py", line 486, in load
    obj = unpickle(fname)
  File "/home/yang/software/Program_File/miniconda3/envs/matchms-python3.8/lib/python3.8/site-packages/gensim/utils.py", line 1460, in unpickle
    with open(fname, 'rb') as f:
  File "/home/yang/software/Program_File/miniconda3/envs/matchms-python3.8/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 177, in open
    fobj = _shortcut_open(
  File "/home/yang/software/Program_File/miniconda3/envs/matchms-python3.8/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 363, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'GNPS_CFMID.min10peaks.model'`

    I've tried changing the parenthesis content at line 322 to a null value, or create a new file in the current directory, and then fill in the file name in the brackets of line 322, but all report an error

How are you using this in your work?

**Comment by volvox292** [comment]
Hi,
I updated the zenodo link with the npy files, this should solve the problem.
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.8114749.svg)](https://doi.org/10.5281/zenodo.8114749)
Otherwise it might be a problem with the version I was using spec2vec 0.6.0. and matchms 0.11.0

Let me know if that works now.

**Comment by oyileo** [comment]
Hi,
thanks for your sharing. But there are new problems, probably missing necessary files again

I downloaded the npy files and put them in the same directory as the model file, and used Python to run the S6 script.

and the error is as follows.

`Loading spectra from pickle objects
Traceback (most recent call last):
  File "S6_matchms_spec2vec.py", line 329, in <module>
    with open("TOTAL_CFMID_MGF.matchms_processed.pickle", "rb") as cfmid, open("David_MGF.min10peaks.mgf.matchms_processed.pickle", "rb") as user:`

In S6 script line 329 and line 330:
`    with open("TOTAL_CFMID_MGF.matchms_processed.pickle", "rb") as cfmid, open("David_MGF.min10peaks.mgf.matchms_processed.pickle", "rb") as user:
        cfmid_spectrums, user_spectrums = pickle.load(cfmid), pickle.load(user)`

Probably I am missing these two files
Could you please upload it again?

Thanks for your giving !

**Comment by volvox292** [comment]
You need to parse the database first with matchms, then you can dump the pickle file. I uploaded the script to do this (matchms_filtering_spectra.py)

**Comment by oyileo** [comment]
Hi,
Thanks your helping and it works now!
