### ISSUE TITLE
No NaMS.msp file

### ISSUE THREAD

**Issue by oyileo** [volvox292/Nicotiana_metabolomics#2]
Hi:
 I'm tring to use matchms
But I don't have NaMS.msp file

Therefore, I am writing for your permission to use your files, and I am wondering if you could kindly send me a copy of it.

Thanks!

![image](https://github.com/volvox292/Nicotiana_metabolomics/assets/137608561/7c95bdfe-6606-41ac-89b0-d4959d743786)

**Comment by volvox292** [comment]
Hi, it is now available !
